"use client";
import {createClient} from "genlayer-js";
import {chain,contractAddress} from "./network";
export type CalldataEncodable=null|boolean|number|bigint|string|Uint8Array|CalldataEncodable[]|Map<string,CalldataEncodable>|{[key:string]:CalldataEncodable};
type Provider={request:(x:{method:string;params?:unknown[]})=>Promise<unknown>};
declare global{interface Window{ethereum?:Provider}}
type Receipt={vote?:string;execution_result?:string};
type Tx={statusName?:string;resultName?:string;txExecutionResultName?:string;consensus_data?:{leader_receipt?:Receipt[];validators?:Array<Record<string,unknown>>}};
type Runtime={readContract:(x:{address:`0x${string}`;functionName:string;args:CalldataEncodable[]})=>Promise<CalldataEncodable>;writeContract:(x:{address:`0x${string}`;functionName:string;args:CalldataEncodable[];value:bigint})=>Promise<string>;waitForTransactionReceipt:(x:{hash:`0x${string}`;status:"FINALIZED";interval:number;retries:number})=>Promise<Tx>};
export async function connect():Promise<string>{if(!window.ethereum)throw new Error("Wallet extension not found");const accounts=await window.ethereum.request({method:"eth_requestAccounts"}) as string[];return accounts[0]||"";}
export async function read(method:string,args:CalldataEncodable[]=[]):Promise<Record<string,unknown>>{const c=createClient({chain}) as unknown as Runtime;const result=await c.readContract({address:contractAddress() as `0x${string}`,functionName:method,args});return JSON.parse(String(result)) as Record<string,unknown>;}
export async function write(account:string,method:string,args:CalldataEncodable[],update:(s:string,h?:string)=>void):Promise<string>{if(!window.ethereum)throw new Error("Wallet extension not found");const c=createClient({chain,provider:window.ethereum,account:account as `0x${string}`}) as unknown as Runtime;update("SIGNING");const hash=await c.writeContract({address:contractAddress() as `0x${string}`,functionName:method,args,value:BigInt(0)});update("CONSENSUS",hash);const tx=await c.waitForTransactionReceipt({hash:hash as `0x${string}`,status:"FINALIZED",interval:2000,retries:300});const leaders=tx.consensus_data?.leader_receipt||[];const agreed=["AGREE","MAJORITY_AGREE"].includes(String(tx.resultName||"").toUpperCase())||leaders.some(r=>String(r.vote||"").toUpperCase()==="AGREE");const returned=String(tx.txExecutionResultName||"").toUpperCase()==="FINISHED_WITH_RETURN"||leaders.some(r=>["SUCCESS","RETURN","FINISHED_WITH_RETURN"].includes(String(r.execution_result||"").toUpperCase()));if(tx.statusName!=="FINALIZED"||!agreed||!returned)throw new Error(`Transaction finalized without agreed successful GenVM return (${tx.resultName||"unknown"}/${tx.txExecutionResultName||"unknown"})`);update("FINALIZED",hash);return hash;}
